title    Spider's LAB (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet splash vt.global_cursor_default=0 loglevel=3 rd.systemd.show_status=auto rd.udev.log_level=3 vt.default_red=0,255,0,255,0,255,0,212,51,255,51,255,51,255,102,255 vt.default_grn=0,0,200,170,102,0,255,212,51,51,255,204,153,102,255,255 vt.default_blu=0,0,0,0,255,255,255,212,51,51,153,51,255,255,255,255
